Models/ErrorViewModel.cs
namespace MvcIntroViews.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MvcIntroViews.Models;

namespace MvcIntroViews.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/OperacoesMatematicasController.cs
using Microsoft.AspNetCore.Mvc;

namespace MvcIntroViews.Controllers;

public class OperacoesMatematicasController : Controller
{
    public IActionResult Somar()
    {
        return View();
    }

    public IActionResult Subtrair()
    {
        return View();
    }

    public IActionResult Multiplicar()
    {
        return View();
    }

    public IActionResult Dividir()
    {
        return View();
    }

    public IActionResult ResultadoSoma([FromForm] double n1, [FromForm] double n2)
    {
        ViewBag.N1 = n1;
        ViewBag.N2 = n2;
        ViewBag.Resultado = n1 + n2;

        return View();
    }

    public IActionResult ResultadoSubtracao([FromForm] double n1, [FromForm] double n2)
    {
        ViewBag.N1 = n1;
        ViewBag.N2 = n2;
        ViewBag.Resultado = n1 - n2;
        
        return View();
    }

    public IActionResult ResultadoMultiplicacao([FromForm] double n1, [FromForm] double n2)
    {
        ViewBag.N1 = n1;
        ViewBag.N2 = n2;
        ViewBag.Resultado = n1 * n2;
        
        return View();
    }

    public IActionResult ResultadoDivisao([FromForm] double n1, [FromForm] double n2)
    {
        ViewBag.N1 = n1;
        ViewBag.N2 = n2;
        ViewBag.Resultado = n1 / n2;
        
        return View();
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/OperacoesMatematicas/Dividir.cshtml
@{
    ViewData["Title"] = "Dividir";
}

<h1>@ViewData["Title"]</h1>
<form action="/OperacoesMatematicas/ResultadoDivisao" method="post">
    <label for="n1">Número 1</label>
    <input type="text" id="n1" name="n1"></input>
    <br><br>
    <label for="n2">Número 2</label>
    <input type="text" id="n2" name="n2"></input>
    <br><br>
    <input type="submit" value="Dividir"></input>
</form>

Views/OperacoesMatematicas/Multiplicar.cshtml
@{
    ViewData["Title"] = "Multiplicar";
}

<h1>@ViewData["Title"]</h1>
<form action="/OperacoesMatematicas/ResultadoMultiplicacao" method="post">
    <label for="n1">Número 1</label>
    <input type="text" id="n1" name="n1"></input>
    <br><br>
    <label for="n2">Número 2</label>
    <input type="text" id="n2" name="n2"></input>
    <br><br>
    <input type="submit" value="Multiplicar"></input>
</form>

Views/OperacoesMatematicas/ResultadoDivisao.cshtml
@{
    ViewData["Title"] = "Resultado Divisão";
}

<h1>@ViewData["Title"]</h1>
<p>A divisão @ViewBag.N1 / @ViewBag.N2 é igual a @ViewBag.Resultado</p>

Views/OperacoesMatematicas/ResultadoMultiplicacao.cshtml
@{
    ViewData["Title"] = "Resultado Multiplicação";
}

<h1>@ViewData["Title"]</h1>
<p>A multiplicação @ViewBag.N1 * @ViewBag.N2 é igual a @ViewBag.Resultado</p>

Views/OperacoesMatematicas/ResultadoSoma.cshtml
@{
    ViewData["Title"] = "Resultado Soma";
}

<h1>@ViewData["Title"]</h1>
<p>A soma @ViewBag.N1 + @ViewBag.N2 é igual a @ViewBag.Resultado</p>

Views/OperacoesMatematicas/ResultadoSubtracao.cshtml
@{
    ViewData["Title"] = "Resultado Subtração";
}

<h1>@ViewData["Title"]</h1>
<p>A subtração @ViewBag.N1 - @ViewBag.N2 é igual a @ViewBag.Resultado</p>

Views/OperacoesMatematicas/Somar.cshtml
@{
    ViewData["Title"] = "Somar";
}

<h1>@ViewData["Title"]</h1>
<form action="/OperacoesMatematicas/ResultadoSoma" method="post">
    <label for="n1">Número 1</label>
    <input type="text" id="n1" name="n1"></input>
    <br><br>
    <label for="n2">Número 2</label>
    <input type="text" id="n2" name="n2"></input>
    <br><br>
    <input type="submit" value="Somar"></input>
</form>

Views/OperacoesMatematicas/Subtrair.cshtml
@{
    ViewData["Title"] = "Subtrair";
}

<h1>@ViewData["Title"]</h1>
<form action="/OperacoesMatematicas/ResultadoSubtracao" method="post">
    <label for="n1">Número 1</label>
    <input type="text" id="n1" name="n1"></input>
    <br><br>
    <label for="n2">Número 2</label>
    <input type="text" id="n2" name="n2"></input>
    <br><br>
    <input type="submit" value="Subtrair"></input>
</form>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcIntroViews</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href},
    "emmet.useInlineCompletions": true="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcIntroViews.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcIntroViews</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="OperacoesMatematicas" asp-action="Somar">Somar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="OperacoesMatematicas" asp-action="Subtrair">Subtrair</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="OperacoesMatematicas" asp-action="Multiplicar">Multiplicar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="OperacoesMatematicas" asp-action="Dividir">Dividir</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MvcIntroViews - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>